apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-gcp-gke-githubactions-cicd-deployment
  labels:
    app: reactapp-gcp-gke-githubactions-cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactapp-gcp-gke-githubactions-cicd
  template:
    metadata:
      labels:
        app: reactapp-gcp-gke-githubactions-cicd
    spec:
      containers:
      - name: react-app
        image: us-central1-docker.pkg.dev/gke-hello-world-498115/react-repo/gcp-gke-githubactions-agrocd-reactapp:e65ae27847edefc5d3159f2ea11a90a4673aebcf
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reactapp-gcp-gke-githubactions-cicd-service
spec:
  type: LoadBalancer
  selector:
    app: reactapp-gcp-gke-githubactions-cicd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80