apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-gcp-gke-githubactions-cicd-deployment
  labels:
    app: reactapp-gcp-gke-githubactions-cicd
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  selector:
    matchLabels:
      app: reactapp-gcp-gke-githubactions-cicd
  template:
    metadata:
      labels:
        app: reactapp-gcp-gke-githubactions-cicd
    spec:
      containers:
      - name: react-app
        image: us-central1-docker.pkg.dev/gke-githubactions-argocd-12345/githubactions-argocd-poc-repo/gcp-gke-githubactions-agrocd-reactapp:8151a4ceca108c86cbc60224ee76f74ead670264
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: reactapp-gcp-gke-githubactions-cicd-service
spec:
  type: LoadBalancer
  selector:
    app: reactapp-gcp-gke-githubactions-cicd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80