apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-gke-githubactions-agrocd-reactapp-deployment
  labels:
    app: gcp-gke-githubactions-agrocd-reactapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcp-gke-githubactions-agrocd-reactapp
  template:
    metadata:
      labels:
        app: gcp-gke-githubactions-agrocd-reactapp
    spec:
      containers:
      - name: react-app
        image: us-central1-docker.pkg.dev/gke-hello-world-498115/react-repo/gcp-gke-githubactions-agrocd-reactapp:v2.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gcp-gke-githubactions-agrocd-reactapp-service
spec:
  type: LoadBalancer
  selector:
    app: gcp-gke-githubactions-agrocd-reactapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80